# swagger.yml

openapi: 3.0.0
info:
  title: "Flask API"
  description: "A test Flask API"
  version: "0.0.1"

servers:
  - url: "/api"

paths:
  /people:
    get:
      operationId: "people.read_all"
      tags:
        - "People"
      summary: "Read list of people"
      responses: 
        "200": 
          description: "Successfully read list of people"
